version: '2'

services:
    tobym:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - REVISION_INFO
        image: vdimir/tobym:latest
        container_name: "tobym"
        hostname: "tobym"
        restart: always

        ports:
            - "127.0.0.1:8443:8443"

        environment:
            - BOT_TOKEN
            - WEB_APP_URL=https://tobym.markify.dev
        volumes:
            - ./var:/srv/var
        labels:
            reproxy.server: '*'
            reproxy.route: '^/(.*)'
            reproxy.dest: '/$$1'

    reproxy:
        image: umputun/reproxy:master
        container_name: reproxy
        hostname: reproxy
        restart: always
        ports:
            - "80:8080"
            - "443:8443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./var/ssl:/srv/var/ssl
        environment:
            - DOCKER_ENABLED=true
            - SSL_TYPE=auto
            - SSL_ACME_LOCATION=/srv/var/ssl
            - SSL_HTTP_PORT=8080
            - SSL_ACME_FQDN=tobym.markify.dev
