name: deploy
on:
  push:
    branches: [master]
    paths:
      - '**'
      - '!README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Package Registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_HOST: tobym.markify.dev
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}"
          ssh -q vdimir@$SSH_HOST "echo ok"

      - name: Build docker image
        run: docker build --build-arg REVISION_INFO="${GITHUB_SHA:0:7}-$(date +%Y%m%d_%H%M%S)" . -t tobym

      - name: Tag and Push image
        run: |
          docker tag tobym vdimir/tobym:latest
          docker push vdimir/tobym:latest

      - name: Deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_HOST: tobym.markify.dev
          WEB_HOOK_URL: https://tobym.markify.dev
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          scp docker-compose.yml vdimir@$SSH_HOST:/srv/tobym
          ssh vdimir@$SSH_HOST "cd /srv/tobym && docker-compose pull"
          ssh vdimir@$SSH_HOST "cd /srv/tobym && BOT_TOKEN=${BOT_TOKEN} WEB_HOOK_URL=${WEB_HOOK_URL} docker-compose up -d"
